# Generated by Django 5.2.10 on 2026-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.BigIntegerField(default=0),
        ),
    ]
